# Generated from Java enums (back.zip) - ordinal mapping (int stored in MySQL -> string in API)

ROL = {0:"ADMIN",1:"PACIENTE",2:"TRABAJADOR",3:"ADMINISTRATIVO",4:"MANTENIMIENTO"}

ESTADO_CITA = {0:"AGENDADA",1:"CANCELADA",2:"PAGADA",3:"COMPLETADA"}

ESTADO_HISTORIA = {0:"ACTIVO",1:"ALTA"}

ENFOQUE = {0:"COGNITIVO",1:"SISTEMICO",2:"PSICODINAMICO",3:"HUMANISTA",4:"INTEGRATIVO"}

FRECUENCIA = {0:"SEMANAL",1:"QUINCENAL",2:"MENSUAL"}

MODALIDAD = {0:"INDIVIDUAL",1:"FAMILIAR",2:"PAREJA",3:"GRUPO"}

CONSUMO = {0:"NUNCA",1:"OCASIONAL",2:"MODERADO",3:"EXCESIVO"}

ESTADO_EMOCION = {0:"MUYBAJO",1:"BAJO",2:"NORMAL",3:"ALTO",4:"MUYALTO"}
