create table antecedentes (id bigint not null auto_increment, paciente_id bigint, estructura varchar(255), eventos varchar(255), trastornos varchar(255), primary key (id)) engine=InnoDB;
create table areas (id bigint not null auto_increment, descripcion varchar(255), imagen varchar(255), nombre varchar(255), primary key (id)) engine=InnoDB;
create table asignacionarea (area_id bigint not null, empleado_id bigint not null, primary key (area_id, empleado_id)) engine=InnoDB;
create table asignacionservicio (area_id bigint not null, servicio_id bigint not null, primary key (area_id, servicio_id)) engine=InnoDB;
create table citas (estado tinyint check ((estado between 0 and 3)), empleado_id bigint, fecha datetime(6), id bigint not null auto_increment, paciente_id bigint, primary key (id)) engine=InnoDB;
create table codigosconfirmacion (tipo integer not null, id bigint not null auto_increment, vencimiento datetime(6) not null, codigo varchar(255) not null, email varchar(255) not null, primary key (id)) engine=InnoDB;
create table descansos (fin time(0), inicio time(0), horario_id bigint, id bigint not null auto_increment, primary key (id)) engine=InnoDB;
create table detalleventa (cantidad integer not null, factura_id bigint, id bigint not null auto_increment, medicamento_id bigint, primary key (id)) engine=InnoDB;
create table diafestivo (dia integer, mes integer, id bigint not null auto_increment, primary key (id)) engine=InnoDB;
create table empleados (aplica_igss bit not null, bono float(53) not null, estado_civil bit not null, fecha_nacimiento date, genero bit not null, sueldo float(53) not null, id bigint not null auto_increment, usuario_id bigint, colegiado varchar(255), nombre varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table empresa (precio_cita float(53) not null, tiempo_cita integer not null, id bigint not null auto_increment, imagen varchar(255), nombre varchar(255), primary key (id)) engine=InnoDB;
create table estadosiniciales (animmo tinyint check ((animmo between 0 and 4)), ansiedad tinyint check ((ansiedad between 0 and 4)), apetito tinyint check ((apetito between 0 and 4)), funcionamientosocial tinyint check ((funcionamientosocial between 0 and 4)), suenio tinyint check ((suenio between 0 and 4)), historia_id bigint, id bigint not null auto_increment, observaciones varchar(255), primary key (id)) engine=InnoDB;
create table historias (costo_sesion float(53) not null, duracion integer not null, enfoque tinyint check ((enfoque between 0 and 4)), estado tinyint check ((estado between 0 and 1)), fecha_apertura date, frecuencia tinyint check ((frecuencia between 0 and 2)), modalidad tinyint check ((modalidad between 0 and 3)), sesiones integer not null, empleado_id bigint, id bigint not null auto_increment, paciente_id bigint, motivo_alta varchar(255), motivo_consulta varchar(255), procedencia varchar(255), primary key (id)) engine=InnoDB;
create table historiaspersonales (alcohol tinyint check ((alcohol between 0 and 3)), drogas tinyint check ((drogas between 0 and 3)), tabaco tinyint check ((tabaco between 0 and 3)), historia_id bigint, id bigint not null auto_increment, desarrollo varchar(255), historia_academica varchar(255), historia_medica varchar(255), hospitalizaciones varchar(255), medicacion_actual varchar(255), tratamientos_previos varchar(255), primary key (id)) engine=InnoDB;
create table horarios (dia integer not null, hora_entrada time(0) not null, hora_salida time(0) not null, trabaja bit not null, empleado_id bigint, id bigint not null auto_increment, primary key (id)) engine=InnoDB;
create table impresiondiagnostica (id bigint not null auto_increment, sesion_id bigint, descripcion varchar(255), factores_mantenedores varchar(255), factores_precipitantes varchar(255), factores_predisponentes varchar(255), nivel_funcionamiento varchar(255), primary key (id)) engine=InnoDB;
create table medicamentos (minimo integer not null, precio float(53) not null, stock integer not null, tipo bit not null, id bigint not null auto_increment, imagen varchar(255), nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table pacientes (estado_civil bit not null, fecha_nacimiento date, genero bit not null, id bigint not null auto_increment, usuario_id bigint, direccion varchar(255), nivel_educativo varchar(255), nombre varchar(255), persona_emergencia varchar(255), procedencia varchar(255), telefono varchar(255), telefono_emergencia varchar(255), primary key (id)) engine=InnoDB;
create table pagosesion (fecha date not null, total float(53) not null, cita_id bigint, id bigint not null auto_increment, sesion_id bigint, codigo varchar(255), fecha_vencimiento varchar(255), tarjeta varchar(255), primary key (id)) engine=InnoDB;
create table pruebasaplicadas (fecha date, resultado float(53) not null, id bigint not null auto_increment, sesion_id bigint, interpretacion varchar(255), primary key (id)) engine=InnoDB;
create table recetas (cantidad integer not null, id bigint not null auto_increment, medicamento_id bigint, paciente_id bigint, sesion bigint not null, indicaciones varchar(255) not null, primary key (id)) engine=InnoDB;
create table servicios (id bigint not null auto_increment, descripcion varchar(255), imagen varchar(255), nombre varchar(255), primary key (id)) engine=InnoDB;
create table sesiones (estado tinyint check ((estado between 0 and 3)), estado_pago bit not null, numero integer not null, fecha datetime(6), historia_id bigint, id bigint not null auto_increment, justificacion varchar(255), observaciones varchar(255), respuestas varchar(255), temas varchar(255), primary key (id)) engine=InnoDB;
create table tareas (estado bit not null, id bigint not null auto_increment, paciente_id bigint, instrucciones varchar(255), primary key (id)) engine=InnoDB;
create table usuarios (a2f bit not null, email_verificado bit not null, estado bit not null, rol tinyint not null check ((rol between 0 and 4)), codigo_verificacion_expira datetime(6), id bigint not null auto_increment, codigo_verificacion varchar(255), email varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table ventas (estado_entrega bit not null, fecha date, total float(53) not null, id bigint not null auto_increment, paciente_id bigint, codigo varchar(255), tarjeta varchar(255), fecha_vencimiento varbinary(255), primary key (id)) engine=InnoDB;
create table verificaciones (id bigint not null auto_increment, codigo varchar(255) not null, email varchar(255) not null, primary key (id)) engine=InnoDB;
alter table antecedentes add constraint UK1gn566y9wxmnmwr9b8w7c8xrd unique (paciente_id);
alter table antecedentes add constraint FKo1fnyqk8wvktlty0fi4vn51kf foreign key (paciente_id) references pacientes (id);
alter table asignacionarea add constraint FKhy76tny0mes7xqwk0kxb73g78 foreign key (area_id) references areas (id);
alter table asignacionarea add constraint FKoijolpoc5r0npuh0eyy40ceh0 foreign key (empleado_id) references empleados (id);
alter table asignacionservicio add constraint FKasdk6exomakywsjfl0ncmjuwp foreign key (area_id) references areas (id);
alter table asignacionservicio add constraint FKrc8athh1384kioqu66jif7ex9 foreign key (servicio_id) references servicios (id);
alter table citas add constraint FKm25vrc2kne6fo0q55xh5aqvm6 foreign key (empleado_id) references empleados (id);
alter table citas add constraint FKnqrsxxcuysfcxiekvixm7h8r1 foreign key (paciente_id) references pacientes (id);
alter table descansos add constraint FK4swbkhth2bn7vgifulnsj7gws foreign key (horario_id) references horarios (id);
alter table detalleventa add constraint FK3712ui1pjbgspkyl7xvojduxl foreign key (factura_id) references ventas (id);
alter table detalleventa add constraint FKmbtulfm4cv1fym14lbi9io3x1 foreign key (medicamento_id) references medicamentos (id);
alter table empleados add constraint FKf5la9sef5mevf72dun7f2rxu4 foreign key (usuario_id) references usuarios (id);
alter table estadosiniciales add constraint FKrhdjlapsatlv7l0a6toa2n6ps foreign key (historia_id) references historias (id);
alter table historias add constraint FKobsoyysodcqhxaf2uhx04qprk foreign key (empleado_id) references empleados (id);
alter table historias add constraint FK1v7qygppy14ckhqsc9xmg6rbh foreign key (paciente_id) references pacientes (id);
alter table historiaspersonales add constraint FKtoiv554f35fww96eax41y78qv foreign key (historia_id) references historias (id);
alter table horarios add constraint FK3jcu7qsdbgrsusnvjxqtdvlbb foreign key (empleado_id) references empleados (id);
alter table impresiondiagnostica add constraint FKt45cfp04r9pvihtdos47anryr foreign key (sesion_id) references sesiones (id);
alter table pacientes add constraint FK96vvhaactwhv7l8ymuq6b4r6j foreign key (usuario_id) references usuarios (id);
alter table pagosesion add constraint FKia5eiqpp7njodjuympp9hm4ei foreign key (cita_id) references citas (id);
alter table pagosesion add constraint FKqetkjgd0ctxx6jyq0xg96tw7m foreign key (sesion_id) references sesiones (id);
alter table pruebasaplicadas add constraint FKrpgdje24swlhq60o5wu4t7r40 foreign key (sesion_id) references sesiones (id);
alter table recetas add constraint FKc9fk8spnlb89wg6r3ffyd97ge foreign key (medicamento_id) references medicamentos (id);
alter table recetas add constraint FKq0k2ukm963ji7cbh835wecte5 foreign key (paciente_id) references pacientes (id);
alter table sesiones add constraint FKlq702lxeaydixby7r61739lpp foreign key (historia_id) references historias (id);
alter table tareas add constraint FKawl1yp660du2m0oamu7bxc9pq foreign key (paciente_id) references pacientes (id);
alter table ventas add constraint FK4qn5dd1fvl4kndmxhqe6wbsuu foreign key (paciente_id) references pacientes (id);
