from .antecedentes import Antecedentes
from .areas import Areas
from .asignacionarea import Asignacionarea
from .asignacionservicio import Asignacionservicio
from .citas import Citas
from .codigosconfirmacion import Codigosconfirmacion
from .descansos import Descansos
from .detalleventa import Detalleventa
from .diafestivo import Diafestivo
from .empleados import Empleados
from .empresa import Empresa
from .estadosiniciales import Estadosiniciales
from .historias import Historias
from .historiaspersonales import Historiaspersonales
from .horarios import Horarios
from .impresiondiagnostica import Impresiondiagnostica
from .medicamentos import Medicamentos
from .pacientes import Pacientes
from .pagosesion import Pagosesion
from .pruebasaplicadas import Pruebasaplicadas
from .recetas import Recetas
from .servicios import Servicios
from .sesiones import Sesiones
from .tareas import Tareas
from .usuarios import Usuarios
from .ventas import Ventas
from .verificaciones import Verificaciones
